name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때만 작동

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy files to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          if [ -z "$EC2_SSH_KEY" ]; then
            echo "Error: EC2 SSH Key is missing!"
            exit 1
          fi
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem
          scp -i ec2_key.pem -r build/ ec2-user@3.27.71.229:/home/ec2-user/react-app
          
      - name: Restart Nginx on EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          ssh -i ec2_key.pem ec2-user@3.27.71.229 'sudo systemctl restart nginx'
          rm ec2_key.pem  # 최종적으로 SSH 키 파일 삭제

